# Site
name: "CoopGroup Robotics"
title: "CoopGroup"
description: "CoopGroup is a coding club teaching kids skills for the future."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl:
mailchimp-list: 'https://coopgroup.us19.list-manage.com/subscribe/post?u=dced7714debf2e05cca0e3abb&amp;id=165be60432'
include: ["_pages"]
permalink: /:title/

# Social media networks
social-media:
  - icon: github
    baseurl: https://github.com
    handle: CoopGroupATX
  - icon: twitter
    baseurl: https://twitter.com
    handle: coop_group
  - icon: discord
    baseurl: https://discord.gg
    handle: ZGxA46u

# Support Us
support-us:
  - title: Patreon
    description: Become a patron and get cool perks when you come to CoopGroup!
    icon: patreon
    icon-type: fab
    baseurl: https://patreon.com
    id: coopgroup
  - title: Teespring
    description: Want a CoopGroup teeshirt or two? Want other cool stuff? Grab some at the CoopGroup Teespring store!
    icon: tshirt
    icon-type: fas
    baseurl: https://coopgroup-3.creator-spring.com
    id:
# Our team
team:
  - name: Cooper Smallwood
    avatar: 'assets/images/cooper.jpg'
    title: Founder & President
    youtube: UCQ_jWBRns1bQWy0VH_zmrlA
    github: CooperSma
    email: cooper.smallwood0@gmail.com
    bio: Hi my name is Cooper. Ever since I was three, I loved coding and robotics. One day, I had an idea to create a robotics club and this is the result.
    other: https://petpleaser.github.io

  - name: Reese Armstrong
    avatar: 'assets/images/reese.jpg'
    title: Vice President
    bio: I'm Reese Armstrong an instructor here who loves helping people with technology, *NIX, and other technologies. I even helped make this website!
    youtube: UCzXRd1MPx__6JjHAeP_9AIA
    github: reesericci

  - name: Arden Smallwood
    avatar: 'assets/images/unnamed.jpg'
    title: Female Outreach
# Dates
dates:
  - image: https://lh3.googleusercontent.com/_4zBNFjA8S9yjNB_ONwqBvxTvyXYdC7Nh1jYZ2x6YEcldBr2fyijdjM2J5EoVdTpnkA
    alt: Customizing Discord
    title: Customizing Discord
    info: We used BandagedBD to customize discord with awesome themes and plugins.
    completed: true

  - image: https://images.unsplash.com/photo-1542831371-29b0f74f9713?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=2000&fit=max&ixid=eyJhcHBfaWQiOjExNzczfQ
    alt: Web Development
    title: Front-end Web Development
    info: We learned the basics of Web Development with HTML, CSS, and Javascript
    completed: true

  - image: https://www.autoauto.ai/wp/wp-content/uploads/2020/05/4386785.jpg
    alt: Self Driving Minuture Car Programming
    title:  Self Driving Minuture Car Programming
    info: Students use Auto-Auto AI cars to learn python.
    completed: true

  - image: https://cdn.instructables.com/FOF/WVU6/JN3HXMRV/FOFWVU6JN3HXMRV.LARGE.jpg?auto=webp&frame=1&width=700&fit=bounds
    alt: Otto Photo
    title: Otto Coding
    info: Programing 3D printed robots (complete).
    completed: true

# Gallery
gallery: 
  - image: '/assets/images/gallery/auto-auto.jpg'
    alt: 'AutoAuto Course Pictures'

# Navigation
nav:
- name: Home
  link: /
- name: About CoopGroup
  link: /about
- name: Support Us
  link: /support-us
- name: Our Team
  link: /our-team
- name: Sign Up
  link: /sign-up
- name: Dates
  link: /dates
- name: Gallery
  link: /gallery

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Other
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true




# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
